### PR TITLE
feat(vue support): support Volar 1.7.0+

### PR DESCRIPTION
**Pull request by Ilanaya**
Since 1.7+ we can't access ts from [plugin context](https://github.com/volarjs/volar.js/compare/v1.6.9...v1.8.0#diff-bcce86ce08673ce17390a21db6f07d1d0e865a39e90a55590c2511a655586753L131)

PR Related changelog refs:
1. [Packages names update](https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#170-202357---pre-release:~:text=rename%20packages%20from)
2. [plugins -> services](volar.config.js plugins option has been renamed to services)

Currently I'm really struggling with how to make plugin work again in the latest version. Definitely gonna investigate soon, but any help is very appreciated

### CODE REVIEW

**Comment by zardoy** [comment]
@maIIady It turns out it was pretty easy to fix, I pushed working version, but of course versions prior 1.7.0 are no longer supported

Changing settings now require server reload, watcher doesnt work for some reason.

Another thing that is not supported is [syntax server features](https://github.com/volarjs/services/blob/d3417ce2f9fceed0a919b65c1e6ad98021c67e7e/packages/typescript/src/index.ts#L188-L191), you can try to add workaround:

```ts
const syntaticLanguageService = typescriptService.provide['typescript/syntacticLanguageService']({
        version: 0,
        getText() {
            return ''
        },
        uri: undefined
    })
```

**Comment by Ilanaya** [comment]
> @maIIady It turns out it was pretty easy to fix, I pushed working version, but of course versions prior 1.7.0 are no longer supported
> 
> Changing settings now require server reload, watcher doesnt work for some reason.
> 
> Another thing that is not supported is [syntax server features](https://github.com/volarjs/services/blob/d3417ce2f9fceed0a919b65c1e6ad98021c67e7e/packages/typescript/src/index.ts#L188-L191), you can try to add workaround:
> 
> ```ts
> const syntaticLanguageService = typescriptService.provide['typescript/syntacticLanguageService']({
>         version: 0,
>         getText() {
>             return ''
>         },
>         uri: undefined
>     })
> ```

I didn't get at all how to implement your workaround and how it should work :(

I checked that it works and updated the related setting implementation but I won't be able to provide support for mentioned features myself

**Comment by zardoy** [comment]
> I checked that it works and updated the related setting implementation but I won't be able to provide support for mentioned features myself

Not a big deal, we can do it later though we can merge now

**Comment by zardoy** [comment]
Will release tomorrow. For now you can install & use extension from latest run of this pr: https://github.com/zardoy/typescript-vscode-plugins/actions/runs/5525801559

**Pull request merged**
