### PR TITLE
feat(refactoring): add/from destructure improvements

### PR DESCRIPTION
**Pull request by Ilanaya**

### CODE REVIEW

**Comment by zardoy** [comment]
since we also do support vue maybe it would be useful to detect cases when we need to wrap the generated result of destruct refactoring with `toRefs`?

**Comment by zardoy** [comment]
This is getting really good!

**Comment by zardoy** [comment]
@Ilanaya i think it's good merge. Tests and handles cases are not bad and want to finally release this so badly :)

**Comment by Ilanaya** [comment]
Agree, I'll complete this feature (add 'this' support and vue refs) when I'll have more spare time(probably this weekend), so if you want you can release it now.

**Comment by zardoy** [comment]
TYSM!

**Pull request merged**
