### PR TITLE
feat: deprecate `changeKindToFunction` in favor of `methodSnippetsInsertText`

### LINKED ISSUE #146: Deprecate `experiments.changeKindToFunction`, replace its functionality with `methodSnippetsInsertText`
e.g. current behavior that can be enabled only with `experiments.changeKindToFunction`, should now also be enabled with `methodSnippetsInsertText` setting. The first setting should be deprecated like `you need to use methodSnippetsInsertText setting instead`

### PR DESCRIPTION
**Pull request by Ilanaya**
Resolves #146

### CODE REVIEW

**Review by zardoy — CHANGES_REQUESTED** [review]

**Comment by Ilanaya** [comment]
@zardoy Hm, I was pretty sure it is working but I didn't manage to run the related tests to get better confidence. Is there a chance to fix them?

**Comment by zardoy** [comment]
do you mean pr checks? no worries everything is fine, these vscode tests unstable sometiems

**Comment by Ilanaya** [comment]
No, actually mean runnig `test-plugin` locally. 
image

**Comment by Ilanaya** [comment]
Ok, that was fun
It was that string which we put in `tsserverlibrary.d.ts` yesterday for testing file creation  :)

**Pull request merged**
