### PR TITLE
feat(refactoring): add/from destructure bug fixes, `this` keyword support

### LINKED ISSUE #167: to destruct, from destruct
- check correct what names would be technically correct
- kind: `refactor.rewrite.add-destruct` and `refactor.rewrite.from-destruct`

Code:

Edge case with to destruct:
```ts
const a = {foo: 5, bar: 8}

const b = [a.foo] // [...] - activation pos range

const c = a
```

```ts
const a = {foo: 5, bar: 8}
const { foo } = a

const b = foo

const c = a
```

With first implementation we can skip hadling this advanced functionality.

### PR DESCRIPTION
**Pull request by Ilanaya**
Closes #167 

- [x] This destructure support
- [x] Support object prop shorthand syntax
- [ ] Vue destructure support
- [ ] in type node: https://github.com/zardoy/vscode-better-snippets/blob/829a6bde0886a007e1cd7daf9a59ce850e601ea6/typescript-plugin/src/index.ts#L29
- [x] Detect and exlude call expressions i.e.
```ts
      function deleteConferenceListEndHandler(deletedConferenceIds) {
        deletedConferenceIds.forEach((deletedConferenceId) => {
          this.conferenceDeletedHandler(deletedConferenceId);
        });
      },
```

### CODE REVIEW

**Comment by Ilanaya** [comment]
@zardoy Can you please help to reproduce the issue with highlights in type nodes? I somehow forgot the case :(

Obviously we shouldn't display code action at all in cases like this (with `typeof`):
```ts
const obj = {
  test: 1,
}
obj.test

type foo = typeof obj

``` 
I'm trying different variations of this code but it works fine...
```ts
type obj = {
  foo: 1,
  obj: 3
}

const test = /** @type {obj} */('asdf')

const obj = {
  test: 1,
}
obj.test
```

**Comment by zardoy** [comment]
@Ilanaya 
This one:
```js
/**
 * 
 * @param a 
 */
const a = (a) => {
    a // here
}
```

**Comment by Ilanaya** [comment]
> @Ilanaya This one:
> 
> ```js
> /**
>  * 
>  * @param a 
>  */
> const a = (a) => {
>     a // here
> }
> ```

@zardoy I can't reproduce with this code and its variations; I may have added stricter checks somewhere. By the way, can we install `prettier` as dev dep in the project? I always get conflicts with the ci's `npx prettier` as it uses prettier v3.1 when [vscode's extension](https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md#1010) currently works with v2 by default

**Comment by zardoy** [comment]
> I can't reproduce with this code and its variations; I may have added stricter checks somewhere. 

ok, feel free to merge.


And what about prettier the answer is yes, i thought prettier was already installed so feel free to do it since npx prefers local packages. btw didn't know they downgraded prettier in the extension

**Comment by Ilanaya** [comment]
Merging now. Vue support needs more effort than I expected.

Can we, please, release it ASAP? This code action version is much more stable than in the current release.

**Pull request merged**
